services:
  foghorn:
    image: zallison/foghorn:latest
    container_name: foghorn
    volumes:
      - /VMData/foghorn:/foghorn/config
    ports:
      - 53:5333/udp
      - 8053:8053
    restart: unless-stopped
