services:
  foghorn:
    network_mode: ${FH_NETWORKMODE:-host}
    image: ${PREFIX:-zallison}/foghorn:${FH_TAG:-latest}
    container_name: ${FH_NAME:-foghorn}
    privileged: true
    volumes:
      - ${FH_CONFIG:-./config}:/foghorn/config
    ports:
      - 53:5335    # TCP/UDP
      - 5380:5380  # Admin/API
      # - 853:1853 # DoT
      # - 443:8153 # DoH
    labels:
      - com.foghorn.priority=${FH_PRIORITY:-200}
    restart: unless-stopped
